In [17]:
print("hello") 

hello


#### 설명글
### 반갑습니다
## 안녕하세요
# 파이썬

In [3]:
import numpy as np

In [4]:
np.arange

<function numpy.arange>

In [7]:
x=np.arange(1,10001)
x2=np.arange(10001,20001)

In [13]:
%%time 
x3=np.zeros_like(x) 
for i in range(10000):
    x3[i]=x[i]+x2[i]

Wall time: 4.96 ms


x와 같은 shape으로 0을 채워라.

 %%time : 실행시간  
 np.zeros_like :x와 같은 shape으로 0을 채워라.

In [14]:
%%time
x3=x+x2

Wall time: 0 ns


14번째 결과와 13번째 결과는 똑같은데 시간은 벡터 연산을 한 14번째 훨씬 적게듬.

In [15]:
np.exp(1)

2.718281828459045

In [18]:
np.exp(2)

7.38905609893065

In [22]:
x=np.array([4,5,6,7])
x.argmin()
x.argmax()

3

argmin() : 최소값의 위치 출력  
argmax() : 최대값의 위치 출력

In [25]:
x=np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
x.sum()
x.sum(axis=0)

array([ 9, 12])

axis=0 : 열 단위로 결과 도출  
axis=1 : 행 단위로 결과 도출

In [33]:
x=np.array([[11,2],[23,14],[5,26]])
print(np.sort(x)) # axis=1 로 줬을때와 동일한 결과
print("*"*50)
print(np.sort(x,axis=0))

[[ 2 11]
 [14 23]
 [ 5 26]]
**************************************************
[[ 5  2]
 [11 14]
 [23 26]]


In [34]:
x

array([[11,  2],
       [23, 14],
       [ 5, 26]])

In [35]:
x=np.array([40,30,10,20])
np.argsort(x) 
#  0  1  2  3       2  3  1  0
#[40,30,10,20] => [10,20,30,40]
# 오름차순 정렬했을때, 원래 데이터의 위치를 출력하는 기능

array([2, 3, 1, 0], dtype=int64)