### 1. 머신러닝 프로젝트 수행과정
1. 문제 정의
    - 프로젝트 목적 : 회원 증가, 카드매출 증대, 생산비용 절감(불량 원인 찾는 작업)
2. 머신러닝을 사용하지 않는 방법 검토
    - 자동 테스트 어려움, 데이터 의존관계 복잡
    - 처리 파이프라인 구조 복잡
3. 시스템 설계
    - 예측 결과를 어떻게 사용
    - 예측 오류의 영향 고려
    - 목표 성능, 포기 지점 설정
4. 알고리즘 선택
    - 군집화 -> 시각화 -> 알고리즘 고민
5. 특징, 로그, 설계
    - 수치벡터, 내일 날씨:비?
    - 특징 변환 : 흐림(1), 맑은 (0)  
      범주 -> 수치 (더미 변수):LableEncoder, OneHotEncoder
6. 데이터 전처리
    - 이상치 처리, 정규화, 빈도가 낮은 단어 제거, 더미변수화, 잡음 제거
7. 학습 및 파라미터 튜닝
    - 과적합 방지(교차검증)
    - 규제화 
    - 학습 곡선
8. 시스템 통합
    - 모니터링
    
### 2. 머신러닝 시스템 문제 해결
- 확률 -> 자동테스트가 어렵다  
- 예측 성능 ↑ => 시스템 복잡 => 유지보수 어려움  
※ 시스템 변화에 잘 대응하는 머신러닝 시스템 구축하는게 목표 
- 예측 모델 -> 모듈화 -> A/B 테스트 수행
- 여러 모델을 모듈화 => 병렬 테스트 

#### 머신러닝 알고리즘 선택 방법
- 분류 : 클래스 (나이브 베이지안, 은닉 마르코프 모델)
- 회귀 : 수치
- 군집화
- 차원축소
- 추천
- 이상탐지
- 강화학습 : 정답이 명확하지 않은 환경에서 앞으로 취하게 될 최적의 행동 선택 

#### 개념
- 퍼셉트론 : 온라인 학습 방식, "선형 분리(초평면)" 가능 문제 해결 가능
- cost 함수 : (실제값-예측값)^2
- 힌지 손실 (hinge=경첩)
- 규제화 : cost도 최소화하고 동시에 가중치도 작게 해줌으로써 과대적합이 되지 않도록 모델을 강제로 제한한다는 의미 (L1, L2 Regularization)
- 신경망
    - 비선형 data 분리 가능
    - 시간 오래 걸림
    - 변수 ↑ => 과적합 ↑
- k-means
- 의사 결정 트리

### 3. 분류 결과 평가 방법
(1) 분류 결과 평가 방법
 - 정밀도, 재현율, f 측정값, 정확도
 - 정확도 : 정답 일치 data / 전제 data
 - 정밀도(precision) : 분류기 -> 스팸으로 판정된 메일 중에서 진짜 스팸의 비율  
 ex) 전체 mail : 100, 스팸으로 판정한 메일:80, 진짜 스팸:60 => 60/80
 - 재현율(recall) : 실제 스팸(60개) 중 분류기가 분류기가 스팸으로 분류(50개) => 50/60
 - f-점수 : 정밀도와 재현율의 조화 평균
 
(2) 예측 결과 평가 방법
 - 평균제곱요차(RMSE)
 - 결정 계수 : 항상 평균을 출력하는 예측 모델보다 성능이 더 좋은가?

In [32]:
import numpy as np

In [33]:
arr=np.arange(0, 4*2*4)
len(arr)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [34]:
v=arr.reshape([4,2,4])
v

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [35]:
v.ndim # 3: 차원의 개수 
v.sum() # 496 : 모든 요소의 합

496

In [36]:
v.sum(axis=0) # 각 행 요소의 합
v.shape #(4, 2, 4)

(4, 2, 4)

In [37]:
v.sum(axis=1) # 각 열 요소의 합

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26],
       [36, 38, 40, 42],
       [52, 54, 56, 58]])

In [38]:
v.sum(axis=2) # 각 깊이 요소의 합

array([[  6,  22],
       [ 38,  54],
       [ 70,  86],
       [102, 118]])

In [39]:
# tf.nn.dynamic_rnn => tf.transepose(대상, [0,2,1])

In [40]:
myTensor=np.arange(2*3*4).reshape(2,3,4)
myTensor
myTensor.shape #(2, 3, 4)

(2, 3, 4)

In [41]:
np.transpose(myTensor).shape # (4, 3, 2)
np.transpose(myTensor)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [42]:
np.transpose(myTensor,[1,2,0]).shape # (2,3,4) -> (3,4,2)

(3, 4, 2)

## keras_mnist based RNN

In [43]:
import tensorflow as tf

In [44]:
from tensorflow.examples.tutorials.mnist import input_data

In [49]:
mnist=input_data.read_data_sets("./mnist2/data/", one_hot=True)

W0822 08:45:53.847342  5456 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:252: _internal_retry.<locals>.wrap.<locals>.wrapped_fn (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please use urllib or similar directly.


Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting ./mnist2/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting ./mnist2/data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting ./mnist2/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting ./mnist2/data/t10k-labels-idx1-ubyte.gz


In [50]:
learning_rate=0.001
total_epoch=30
batch_size=128

In [51]:
n_input=28 # 가로 픽셀수
n_step=28  # 세로 픽셀수(입력단계, step)
n_hidden=128 
n_class=10

In [52]:
tf.reset_default_graph()
x = tf.placeholder(tf.float32, [None, n_step, n_input])
y = tf.placeholder(tf.float32, [None, n_class])
w = tf.Variable(tf.random_normal([n_hidden, n_class]))
b = tf.Variable(tf.random_normal([n_class]))

In [53]:
cell = tf.nn.rnn_cell.BasicRNNCell(n_hidden)
outputs, states = tf.nn.dynamic_rnn(cell, x, dtype=tf.float32)
# Y: [batch_size, nclass]
# outputs: [batch_size, n_step, n_hidden]
# [n_step, batch_size, n_hidden]
# [batch_size, n_hidden]
outputs = tf.transpose(outputs, [1, 0, 2]) # [n_step, batch_size, n_hidden]
outputs = outputs[-1] # [batch_size, n_hidden]
model = tf.matmul(outputs, w) + b
# tf.matmul([batch_size, n_hidden], [n_hidden, n_class])

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=y))
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [54]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
total_batch = int(mnist.train.num_examples/batch_size)
for epoch in range(total_epoch):
    total_cost = 0
    for i in range(total_batch):
        batch_xs, batch_ys = mnist.train.next_batch(batch_size)
        # [batch_size, n_step, n_input]
        batch_xs = batch_xs.reshape((batch_size, n_step, n_input))
        _, cv = sess.run([optimizer, cost], feed_dict={x: batch_xs, y: batch_ys})
        total_cost += cv
    print("epoch ", "%4d" % (epoch+1),
         "avg cost", "{:.3f}".format(total_cost/total_batch))

epoch     1 avg cost 0.553
epoch     2 avg cost 0.234
epoch     3 avg cost 0.175
epoch     4 avg cost 0.155
epoch     5 avg cost 0.139
epoch     6 avg cost 0.119
epoch     7 avg cost 0.116
epoch     8 avg cost 0.120
epoch     9 avg cost 0.104
epoch    10 avg cost 0.105
epoch    11 avg cost 0.097
epoch    12 avg cost 0.090
epoch    13 avg cost 0.091
epoch    14 avg cost 0.083
epoch    15 avg cost 0.079
epoch    16 avg cost 0.074
epoch    17 avg cost 0.084
epoch    18 avg cost 0.081
epoch    19 avg cost 0.078
epoch    20 avg cost 0.075
epoch    21 avg cost 0.071
epoch    22 avg cost 0.070
epoch    23 avg cost 0.067
epoch    24 avg cost 0.070
epoch    25 avg cost 0.064
epoch    26 avg cost 0.067
epoch    27 avg cost 0.072
epoch    28 avg cost 0.069
epoch    29 avg cost 0.059
epoch    30 avg cost 0.056


In [55]:
is_correct = tf.equal(tf.argmax(model, 1), tf.argmax(y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

test_batch_size = len(mnist.test.images)
test_xs = mnist.test.images.reshape(test_batch_size, n_step, n_input)
test_ys = mnist.test.labels

print("정확도: ", sess.run(accuracy, feed_dict={x: test_xs, y: test_ys}))

정확도:  0.965


In [56]:
# {'a':0,....,'z':25}
char_arr = ['a', 'b', 'c', 'd', 'e', 'f', 'g',
            'h', 'i', 'j', 'k', 'l', 'm', 'n',
            'o', 'p', 'q', 'r', 's', 't', 'u',
            'v', 'w', 'x', 'y', 'z']
num_dic={n:i for i,n in enumerate(char_arr)}
num_dic

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [ ]:
# {'test','free','make','show','take','four'}
# 입력 : tes(3글자)
# 출력 : est(1글자)
# 1. 단어를 글자단위(voc)로 나눔. 원핫인코딩
# 2. 트레이닝