In [13]:
# 클래스: 함수와 변수로 구성
class MulLayer:
    def __init__(self):
        self.x=None
        self.y=None
        
    def forward(self,x,y):
        self.x=x
        self.y=y
        out=x*y
        return out
    
    def backward(self,dout):
        dx=dout*self.y
        dy=dout*self.x
        return dx,dy

In [14]:
# 객체 생성
# 객체를 생성할 때, 초기화해주기 위해서 선언
# 이때는 def __init__(self)가 불려져 나옴
mal=MulLayer()
mtl=MulLayer()

In [15]:
# 순전파
apple=100
apple_num=2
tax=1.1
apple_price=mal.forward(apple,apple_num) # mal 객체의 x변수:100, mal 객체의 y 변수:2 저장
price=mtl.forward(apple_price, tax)  # mtl 객체의 x변수:200, mal 객체의 y 변수:1.1 저장
print("price:", int(price))

price: 220


In [17]:
# 역전파
dprice=1
dapple_price,dtax=mtl.backward(dprice) 
# print(dapple_price,dtax)
dapple, dapple_num=mal.backward(dapple_price)
print(dapple,dapple_num,dapple_price)

2.2 110.00000000000001 1.1


### 상수형(constant)

In [18]:
# 상수형(constant)
import tensorflow as tf

In [26]:
a=tf.constant([5],dtype=tf.float32) # 주로 float 타입이 쓰임, tf.constant([5.])
b=tf.constant([10],dtype=tf.float32) 
c=tf.constant([2],dtype=tf.float32) 
c # 정보 출력
d=a*b+c
d # d에 대한 정보만 출력
# tf.constant는 노드를 의미하고 a,b,c는 노드의 이름을 나타내고 tf.value는 엣지를 의미
# 노드는 연산을 하는데 데이터를 보관하고 있는 것도 연산으로 봄
# 뉴런에서 신호(tensor)가 엣지이고 뉴런 자체가 노드를 나타냄
# 코딩한 것도 그래프를 그렸다고 할 수 있음
# 그래프를 실행하면 순차적으로 진행됨

<tf.Tensor 'add_4:0' shape=(1,) dtype=float32>

In [27]:
# 세션을 생성해서 그래프 실행
# 세션:그래프를 실행시켜주는 runner
sess=tf.Session() # 세션 생성, Session은 클래스 
sess.run(a) # array([5.], dtype=float32)
print(sess.run(a)) # [5.] => print로 묶여줘야 보기에 편함
print(sess.run(d))
# 실행을 하게 되면 바로 a*b+c로 계산되는 것이 아니라, 
#a*b 부터 진행하기 위해 역으로 돌아가 a,b를 가져와 수식을 진행하고, 그 다음 c를 가져와 a*b와 c를 가져와 더하기 연산을 진행한다. 

[5.]
[52.]


### 플레이스 홀더 : 학습용 데이터를 임시로 보관하는 저장소
    - y=x*2
    - 그래프를 실행시키는 이유는 모델을 만들기 위해서이고(모델을 만드는 것을 training 이라 함)
    - 그래프가 실행되어야만 training 되고 최종적으로 모델을 만들 수 있음
    - 그래프 실행을 위해서는 데이터가 있어야하고, 데이터를 임시로 보관하는 곳이 '플레이스 홀더' 라고함
    - y=x*2 모델을 실행시키려면 x라는 플레이스 홀더에 훈련하고자하는 데이터를 전달해줘야함

In [36]:
x=tf.placeholder(dtype=tf.float32) # 플레이스 홀더 
data=[1,2,3,4]
y=x*2 # 브로드캐스팅 
print(sess.run(y,feed_dict={x:data})) # 그래프를 실행하는 코드
# 피딩(feeding):학습용 데이터를 딕셔너리 형태로 전달하는 행위(그래프를 실행하는 시점에 전달해줘함)
# 학습용 데이터는 딕셔너리 형태로 전달해줘야함 {전달받는 플레이스 홀더: 값(리스트,배열 등 )}

[2. 4. 6. 8.]


### 변수(Variable)
    - 훈련(트레이닝, 모델링)과정에서 변화하는 기울기, 절편 등을 의미
    - hf=wx+b
    - hf=0.5x+2
    - w,b는 변수
    - 변수는 초기화해줘야함

In [43]:
inputData=[1,2,3]
x=tf.placeholder(dtype=tf.float32)
w=tf.Variable([2],dtype=tf.float32) # 초기값 2, w는 계속 갱신될 것이므로 변수로 설정해줘야함
yhat=w*x

sess=tf.Session()
sess.run(tf.global_variables_initializer()) # 변수를 쓸 때는 반드시 초기화를 해줘야함
# 변수가 있을 때 세션 객체를 생성 후 항상 써줘야함
# init=tf.global_variables_initializer()
# sess.run(init) # 초기화 해주는 것과 똑같은 형태

sess.run(yhat,feed_dict={x:inputData})

array([2., 4., 6.], dtype=float32)

In [57]:
# tf.matmul(행렬,행렬) : 행렬의 곱셈을 하는 함수, 행렬의 내적을 한 결과가 나옴
# [1 2 3]*[2 2 2].T =[12]
x=tf.constant([[1,2,3]])
w=tf.constant([[2],[2],[2]])
y=tf.matmul(x,w)
print(sess.run(y)[0][0]) # 2차원으로 출력되므로 [0][0]이면 대괄호가 벗겨지고 숫자만 출력

12


In [61]:
x=tf.Variable([[1,2,3]])
w=tf.constant([[2],[2],[2]])
y=tf.matmul(x,w)
init=tf.global_variables_initializer()
sess.run(init) 
sess.run(y)

array([[12]])

In [62]:
x=tf.Variable([[1,2,3],[1,2,3],[2,3,4]])
w=tf.constant([[2],[2],[2]])
y=tf.matmul(x,w)
init=tf.global_variables_initializer()
sess.run(init) 
sess.run(y)

array([[12],
       [12],
       [18]])

In [64]:
# tensorflow에서 None은 아직 결정되지 않은 상태를 의미
indata=[[1,2,3],[1,2,3],[2,3,4]]
x=tf.placeholder(dtype=tf.float32, shape=[None,3]) 
# shape=[None,3]:열은 3개로 고정되어 있는데 행은 잘 아직 결정된게 없다는 의미, 보통 None으로 쓰는게 일반적
# 그럼 알아서 데이터를 읽으면서 행 자리를 대체해줌
w=tf.constant([[2],[2],[2]],dtype=tf.float32)
y=tf.matmul(x,w) #3*3 . 3*1 => 3*1
init=tf.global_variables_initializer()
sess.run(init) 
sess.run(y,feed_dict={x:indata}) # 3행 3열

array([[12.],
       [12.],
       [18.]], dtype=float32)

In [67]:
# 브로드캐스팅 : tensortflow에서도 가능
data=[[1,1,1],[2,2,2]]
x=tf.placeholder(dtype=tf.float32, shape=[None,3])
w=tf.Variable([[2],[2],[2]], dtype=tf.float32)
b=tf.Variable([4],dtype=tf.float32)
y=tf.matmul(x,w)+b # 2*3 3*1=> 2*1
# 1 1 1  2
# 2 2 2  2   => 6+4  10
#        2   => 12+4 16
sess=tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(y,feed_dict={x:data})

array([[10.],
       [16.]], dtype=float32)

In [68]:
# 연습문제
apple=100
appleNum=2
orange=150
orangeNum=3
tax=1.1
# forward: 값 출력 /backward : 5개의 변수들의 영향력 출력
# price 출력:(100*2+150*3)*1.1
# dapple : apple 영향력
# dappleNum : 
# dorange
# dorangeNum
# dtax

In [ ]:
def googoo(dan):
    5*1=5
    5*9=45